syntax = "proto3";

package auth;

option go_package = "./";

import "google/protobuf/timestamp.proto";

service AuthService {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc UpdatePassword(UpdatePasswordRequest) returns (UpdatePasswordResponse);
}

message RegisterRequest {
    string username = 1;
    string password = 2;
}

message RegisterResponse {
    string message = 1;
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    string accesstoken = 1;
    string refreshtoken = 2;
}

message UpdatePasswordRequest {
    int64 user_id = 1;
    string password = 2;
    string new_password = 3;
}

message UpdatePasswordResponse {
    string message = 1;
}

message Err {
    google.protobuf.Timestamp expiration_time = 1;
}
